CREATE DATABASE IF NOT EXISTS matrix_erp
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_order (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '采购订单号',
    fdate DATE NOT NULL COMMENT '采购订单日期',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '供应商BusinessPartner ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '供应商名称快照',
    fcontract_id BIGINT NULL COMMENT '采购合同ID',
    fcurrency_id BIGINT NULL COMMENT '币种ID',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '币种编码快照',
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '订单总数量',
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '不含税金额',
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '价税合计',
    fpayment_term_code VARCHAR(64) NULL COMMENT '付款条件编码',
    fplanned_delivery_date DATE NULL COMMENT '计划交货日期',
    fstatus VARCHAR(32) NOT NULL COMMENT '生命周期状态',
    fapproval_status VARCHAR(32) NOT NULL COMMENT '审批状态',
    freceipt_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '收货状态',
    finvoice_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '开票状态',
    fsettlement_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '结算状态',
    fclose_status VARCHAR(32) NOT NULL DEFAULT 'OPEN' COMMENT '关闭状态',
    fcreate_by BIGINT NULL COMMENT '创建人ID',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人ID',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_order_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_purchase_order_partner (ftenant_id, fbusiness_partner_id),
    KEY idx_matrix_erp_purchase_order_status (ftenant_id, forg_id, fstatus, fapproval_status),
    KEY idx_matrix_erp_purchase_order_date (ftenant_id, fdate)
) COMMENT='采购订单主表';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_order_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fpurchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    fline_no INT NOT NULL COMMENT '行号',
    fmaterial_id BIGINT NOT NULL COMMENT '物料ID',
    fmaterial_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
    fmaterial_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
    fspecification VARCHAR(255) NULL COMMENT '规格型号快照',
    funit_id BIGINT NULL COMMENT '计量单位ID',
    fquantity DECIMAL(20,6) NOT NULL COMMENT '采购数量',
    funit_price DECIMAL(20,6) NOT NULL COMMENT '不含税单价',
    fnet_amount DECIMAL(20,2) NOT NULL COMMENT '不含税金额',
    ftax_rate DECIMAL(10,6) NOT NULL DEFAULT 0 COMMENT '税率，0~1小数',
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL COMMENT '价税合计',
    fplanned_delivery_date DATE NULL COMMENT '计划交货日期',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    freceived_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计收货数量',
    faccepted_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计验收数量',
    finbound_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计入库数量',
    finvoiced_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计开票数量',
    fsettled_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '累计结算金额',
    fcreate_by BIGINT NULL COMMENT '创建人ID',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人ID',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_order_entry_order (fpurchase_order_id, fline_no),
    KEY idx_matrix_erp_purchase_order_entry_material (ftenant_id, fmaterial_id),
    KEY idx_matrix_erp_purchase_order_entry_project (ftenant_id, fproject_id)
) COMMENT='采购订单分录表';
