spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 默认激活 dev 环境

  config:
    import: "nacos:${spring.application.name}"  # 从 Nacos 加载配置

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:117.72.216.168:8848}     # 默认本地
        group: ${NACOS_GROUP:DEV_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        server-addr: ${NACOS_ADDR:117.72.216.168:8848}
        file-extension: yaml
        group: ${NACOS_GROUP:DEV_GROUP}
        namespace: ${NACOS_NAMESPACE:public}
