CREATE DATABASE IF NOT EXISTS matrix_erp
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE matrix_erp;

-- P0-IMP-02：采购订单行增加收货预占，防止并发超收。
ALTER TABLE matrix_erp_purchase_order_entry
    ADD COLUMN freceipt_reserved_quantity DECIMAL(20,6) NOT NULL DEFAULT 0
    COMMENT '收货草稿/下推预占数量' AFTER fcost_center_id;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_receipt (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fsupplier_delivery_no VARCHAR(128) NULL,
    fwarehouse_id BIGINT NULL,
    fstatus VARCHAR(32) NOT NULL,
    fapproval_status VARCHAR(32) NOT NULL,
    fbotp_idempotency_key VARCHAR(255) NULL,
    fsource_execution_id VARCHAR(64) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_receipt_number (ftenant_id, fnumber),
    UNIQUE KEY uk_matrix_erp_purchase_receipt_botp (ftenant_id, fbotp_idempotency_key),
    KEY idx_matrix_erp_purchase_receipt_partner (ftenant_id, fbusiness_partner_id),
    KEY idx_matrix_erp_purchase_receipt_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='采购收货单';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_receipt_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpurchase_receipt_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    fbatch_no VARCHAR(128) NULL,
    fwarehouse_id BIGINT NULL,
    finspection_reserved_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    finspected_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_receipt_entry_header (fpurchase_receipt_id, fline_no),
    KEY idx_matrix_erp_purchase_receipt_entry_order (ftenant_id, fpurchase_order_entry_id)
) COMMENT='采购收货单分录';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_acceptance (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fpurchase_receipt_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fstatus VARCHAR(32) NOT NULL,
    fapproval_status VARCHAR(32) NOT NULL,
    fresult VARCHAR(32) NOT NULL,
    fbotp_idempotency_key VARCHAR(255) NULL,
    fsource_execution_id VARCHAR(64) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_acceptance_number (ftenant_id, fnumber),
    UNIQUE KEY uk_matrix_erp_purchase_acceptance_botp (ftenant_id, fbotp_idempotency_key),
    KEY idx_matrix_erp_purchase_acceptance_receipt (ftenant_id, fpurchase_receipt_id),
    KEY idx_matrix_erp_purchase_acceptance_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='采购验收单';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_acceptance_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpurchase_acceptance_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_receipt_id BIGINT NOT NULL,
    fpurchase_receipt_entry_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    finspection_quantity DECIMAL(20,6) NOT NULL,
    fqualified_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fconcession_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    frejected_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    finspection_method VARCHAR(64) NULL,
    fquality_result VARCHAR(32) NOT NULL,
    fbatch_no VARCHAR(128) NULL,
    funit_price DECIMAL(20,6) NOT NULL DEFAULT 0,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    finbound_reserved_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    finbound_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_acceptance_entry_header (fpurchase_acceptance_id, fline_no),
    KEY idx_matrix_erp_purchase_acceptance_entry_receipt (ftenant_id, fpurchase_receipt_entry_id),
    KEY idx_matrix_erp_purchase_acceptance_entry_order (ftenant_id, fpurchase_order_entry_id)
) COMMENT='采购验收单分录';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_inbound (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fpurchase_acceptance_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fwarehouse_id BIGINT NULL,
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    ftotal_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL,
    fapproval_status VARCHAR(32) NOT NULL,
    faccounting_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    fbotp_idempotency_key VARCHAR(255) NULL,
    fsource_execution_id VARCHAR(64) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_inbound_number (ftenant_id, fnumber),
    UNIQUE KEY uk_matrix_erp_purchase_inbound_botp (ftenant_id, fbotp_idempotency_key),
    KEY idx_matrix_erp_purchase_inbound_acceptance (ftenant_id, fpurchase_acceptance_id),
    KEY idx_matrix_erp_purchase_inbound_accounting (ftenant_id, faccounting_status, fdate)
) COMMENT='采购入库单';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_inbound_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpurchase_inbound_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_acceptance_id BIGINT NOT NULL,
    fpurchase_acceptance_entry_id BIGINT NOT NULL,
    fpurchase_receipt_entry_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    fbatch_no VARCHAR(128) NULL,
    fwarehouse_id BIGINT NULL,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_inbound_entry_header (fpurchase_inbound_id, fline_no),
    KEY idx_matrix_erp_purchase_inbound_entry_acceptance (ftenant_id, fpurchase_acceptance_entry_id),
    KEY idx_matrix_erp_purchase_inbound_entry_order (ftenant_id, fpurchase_order_entry_id)
) COMMENT='采购入库单分录';

CREATE TABLE IF NOT EXISTS matrix_erp_business_event_outbox (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fevent_id VARCHAR(64) NOT NULL,
    fevent_type VARCHAR(128) NOT NULL,
    fevent_version INT NOT NULL,
    fproducer_service VARCHAR(64) NOT NULL,
    fdomain_code VARCHAR(64) NOT NULL,
    faggregate_type VARCHAR(64) NOT NULL,
    faggregate_id VARCHAR(128) NOT NULL,
    faggregate_version BIGINT NOT NULL,
    fsource_system_code VARCHAR(64) NULL,
    fsource_document_type VARCHAR(64) NULL,
    fsource_document_id VARCHAR(128) NULL,
    fsource_document_no VARCHAR(128) NULL,
    fbusiness_date DATE NULL,
    fcorrelation_id VARCHAR(128) NULL,
    fcausation_id VARCHAR(128) NULL,
    ftrace_id VARCHAR(128) NULL,
    foperator_id BIGINT NULL,
    frouting_key VARCHAR(255) NOT NULL,
    fpayload_json JSON NOT NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    fretry_count INT NOT NULL DEFAULT 0,
    fmax_retry INT NOT NULL DEFAULT 10,
    fnext_retry_time DATETIME NULL,
    fclaim_token VARCHAR(128) NULL,
    fclaim_time DATETIME NULL,
    fsent_time DATETIME NULL,
    flast_error VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_business_event_id (fevent_id),
    UNIQUE KEY uk_matrix_erp_business_event_fact
        (ftenant_id, faggregate_type, faggregate_id, faggregate_version, fevent_type, fdelete_flag),
    KEY idx_matrix_erp_business_event_dispatch (fstatus, fnext_retry_time, fcreate_time)
) COMMENT='ERP业务事件Outbox';
