CREATE DATABASE IF NOT EXISTS matrix_botp
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE matrix_botp;

CREATE TABLE IF NOT EXISTS matrix_botp_document_type (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fsystem_code VARCHAR(64) NOT NULL COMMENT '系统编码',
    fcode VARCHAR(64) NOT NULL COMMENT '单据类型编码',
    fname VARCHAR(128) NOT NULL COMMENT '单据类型名称',
    fservice_code VARCHAR(64) NULL COMMENT '服务编码',
    fadapter_code VARCHAR(128) NOT NULL COMMENT '适配器编码',
    fstatus VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '状态',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_document_type (ftenant_id, fsystem_code, fcode, fdelete_flag),
    KEY idx_matrix_botp_document_type_adapter (fadapter_code)
) COMMENT='BOTP单据类型';

CREATE TABLE IF NOT EXISTS matrix_botp_document_field (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fdocument_type_id BIGINT NOT NULL COMMENT '单据类型ID',
    fentity_level VARCHAR(32) NOT NULL COMMENT 'HEADER或ENTRY',
    fcode VARCHAR(128) NOT NULL COMMENT '字段编码',
    fname VARCHAR(128) NOT NULL COMMENT '字段名称',
    ffield_type VARCHAR(32) NOT NULL COMMENT '字段类型',
    frequired TINYINT NOT NULL DEFAULT 0 COMMENT '是否必填',
    freadonly TINYINT NOT NULL DEFAULT 0 COMMENT '是否只读',
    fprecision_value INT NULL COMMENT '精度',
    fscale_value INT NULL COMMENT '小数位',
    fmetadata_json JSON NULL COMMENT '扩展元数据',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_document_field (fdocument_type_id, fentity_level, fcode, fdelete_flag),
    KEY idx_matrix_botp_document_field_type (ftenant_id, fdocument_type_id)
) COMMENT='BOTP单据字段元数据';

CREATE TABLE IF NOT EXISTS matrix_botp_conversion_rule (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fcode VARCHAR(64) NOT NULL COMMENT '规则编码',
    fname VARCHAR(128) NOT NULL COMMENT '规则名称',
    fsource_system_code VARCHAR(64) NOT NULL COMMENT '源系统编码',
    fsource_document_type VARCHAR(64) NOT NULL COMMENT '源单类型',
    ftarget_system_code VARCHAR(64) NOT NULL COMMENT '目标系统编码',
    ftarget_document_type VARCHAR(64) NOT NULL COMMENT '目标单类型',
    fcurrent_version INT NOT NULL DEFAULT 0 COMMENT '当前版本',
    fstatus VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_conversion_rule (ftenant_id, fcode, fdelete_flag),
    KEY idx_matrix_botp_conversion_rule_source (ftenant_id, fsource_system_code, fsource_document_type),
    KEY idx_matrix_botp_conversion_rule_target (ftenant_id, ftarget_system_code, ftarget_document_type)
) COMMENT='BOTP转换规则';

CREATE TABLE IF NOT EXISTS matrix_botp_rule_version (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    frule_id BIGINT NOT NULL COMMENT '规则ID',
    frule_code VARCHAR(64) NOT NULL COMMENT '规则编码快照',
    fversion_no INT NOT NULL COMMENT '版本号',
    fstatus VARCHAR(32) NOT NULL COMMENT '版本状态',
    fdefinition_json JSON NOT NULL COMMENT '不可变规则快照',
    fpersist_hash VARCHAR(128) NOT NULL COMMENT '规则快照哈希',
    fpublished_by BIGINT NULL COMMENT '发布人',
    fpublished_time DATETIME NULL COMMENT '发布时间',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_rule_version (ftenant_id, frule_code, fversion_no, fdelete_flag),
    KEY idx_matrix_botp_rule_version_rule (frule_id, fstatus)
) COMMENT='BOTP规则版本';

CREATE TABLE IF NOT EXISTS matrix_botp_field_mapping (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    frule_version_id BIGINT NOT NULL COMMENT '规则版本ID',
    fmapping_scope VARCHAR(32) NOT NULL COMMENT 'HEADER、ENTRY或WRITEBACK',
    fsource_type VARCHAR(32) NOT NULL COMMENT 'SOURCE_FIELD、CONSTANT或CONTEXT',
    fsource_path VARCHAR(255) NULL COMMENT '源路径',
    ftarget_path VARCHAR(255) NOT NULL COMMENT '目标路径',
    fconstant_json JSON NULL COMMENT '常量值',
    frequired TINYINT NOT NULL DEFAULT 0 COMMENT '是否必填',
    fsort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_botp_field_mapping_version (frule_version_id, fmapping_scope, fsort_no)
) COMMENT='BOTP字段映射';

CREATE TABLE IF NOT EXISTS matrix_botp_execution (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fexecution_id VARCHAR(64) NOT NULL COMMENT '执行ID',
    fsource_system VARCHAR(64) NOT NULL COMMENT '调用来源系统',
    frequest_id VARCHAR(128) NOT NULL COMMENT '调用方请求号',
    frule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    frule_version INT NOT NULL COMMENT '规则版本',
    fexecution_mode VARCHAR(32) NOT NULL COMMENT '执行模式',
    fstatus VARCHAR(32) NOT NULL COMMENT '执行状态',
    frequest_json JSON NOT NULL COMMENT '执行请求快照',
    ferror_message VARCHAR(1000) NULL COMMENT '错误信息',
    fretry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    fstart_time DATETIME NOT NULL COMMENT '开始时间',
    ffinish_time DATETIME NULL COMMENT '完成时间',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_execution_id (fexecution_id),
    UNIQUE KEY uk_matrix_botp_execution_request (ftenant_id, fsource_system, frequest_id, fdelete_flag),
    KEY idx_matrix_botp_execution_rule_status (ftenant_id, frule_code, fstatus, fcreate_time)
) COMMENT='BOTP执行任务';

CREATE TABLE IF NOT EXISTS matrix_botp_execution_target (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fexecution_id VARCHAR(64) NOT NULL COMMENT '执行ID',
    ftarget_index INT NOT NULL COMMENT '目标序号',
    ftarget_idempotency_key VARCHAR(255) NOT NULL COMMENT '目标创建幂等键',
    ftarget_system_code VARCHAR(64) NOT NULL COMMENT '目标系统',
    ftarget_document_type VARCHAR(64) NOT NULL COMMENT '目标单类型',
    ftarget_document_id VARCHAR(128) NULL COMMENT '目标单ID',
    ftarget_document_no VARCHAR(128) NULL COMMENT '目标单号',
    fstatus VARCHAR(32) NOT NULL COMMENT '目标创建状态',
    fresponse_json JSON NULL COMMENT '目标响应快照',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_botp_execution_target_key (ftarget_idempotency_key),
    UNIQUE KEY uk_matrix_botp_execution_target_index (fexecution_id, ftarget_index, fdelete_flag),
    KEY idx_matrix_botp_execution_target_document (ftenant_id, ftarget_system_code, ftarget_document_type, ftarget_document_id)
) COMMENT='BOTP执行目标结果';

CREATE TABLE IF NOT EXISTS matrix_botp_document_relation (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fexecution_id VARCHAR(64) NOT NULL COMMENT '执行ID',
    frule_code VARCHAR(64) NOT NULL COMMENT '规则编码',
    frule_version INT NOT NULL COMMENT '规则版本',
    fsource_system_code VARCHAR(64) NOT NULL COMMENT '源系统',
    fsource_document_type VARCHAR(64) NOT NULL COMMENT '源单类型',
    fsource_document_id VARCHAR(128) NOT NULL COMMENT '源单ID',
    ftarget_system_code VARCHAR(64) NOT NULL COMMENT '目标系统',
    ftarget_document_type VARCHAR(64) NOT NULL COMMENT '目标单类型',
    ftarget_document_id VARCHAR(128) NOT NULL COMMENT '目标单ID',
    frelation_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '关系状态',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_botp_relation_source (ftenant_id, fsource_system_code, fsource_document_type, fsource_document_id, frelation_status),
    KEY idx_matrix_botp_relation_target (ftenant_id, ftarget_system_code, ftarget_document_type, ftarget_document_id, frelation_status),
    KEY idx_matrix_botp_relation_execution (fexecution_id)
) COMMENT='BOTP单据上下游关系';

CREATE TABLE IF NOT EXISTS matrix_botp_document_relation_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    frelation_id BIGINT NOT NULL COMMENT '单头关系ID',
    fsource_entry_id VARCHAR(128) NOT NULL COMMENT '源分录ID',
    ftarget_entry_id VARCHAR(128) NOT NULL COMMENT '目标分录ID',
    fquantity DECIMAL(23, 10) NULL COMMENT '关联数量',
    famount DECIMAL(23, 10) NULL COMMENT '关联金额',
    fbase_quantity DECIMAL(23, 10) NULL COMMENT '基本数量',
    fbase_amount DECIMAL(23, 10) NULL COMMENT '本位币金额',
    frelation_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '关系状态',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_botp_relation_entry_source (ftenant_id, fsource_entry_id, frelation_status),
    KEY idx_matrix_botp_relation_entry_target (ftenant_id, ftarget_entry_id, frelation_status),
    KEY idx_matrix_botp_relation_entry_relation (frelation_id)
) COMMENT='BOTP分录关联关系';

CREATE TABLE IF NOT EXISTS matrix_botp_writeback_task (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    fexecution_id VARCHAR(64) NOT NULL COMMENT '执行ID',
    frelation_id BIGINT NULL COMMENT '关系ID',
    fsource_system_code VARCHAR(64) NOT NULL COMMENT '源系统',
    fsource_document_type VARCHAR(64) NOT NULL COMMENT '源单类型',
    fsource_document_id VARCHAR(128) NOT NULL COMMENT '源单ID',
    fstatus VARCHAR(32) NOT NULL COMMENT '反写状态',
    fcommand_json JSON NOT NULL COMMENT '反写命令',
    fretry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    fnext_retry_time DATETIME NULL COMMENT '下次重试时间',
    ferror_message VARCHAR(1000) NULL COMMENT '错误信息',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_botp_writeback_retry (fstatus, fnext_retry_time),
    KEY idx_matrix_botp_writeback_execution (fexecution_id)
) COMMENT='BOTP反写任务';

CREATE TABLE IF NOT EXISTS matrix_botp_outbox_event (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    faggregate_type VARCHAR(64) NOT NULL COMMENT '聚合类型',
    faggregate_id VARCHAR(128) NOT NULL COMMENT '聚合ID',
    fevent_type VARCHAR(128) NOT NULL COMMENT '事件类型',
    fpayload_json JSON NOT NULL COMMENT '事件载荷',
    fstatus VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '投递状态',
    fretry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    fnext_retry_time DATETIME NULL COMMENT '下次重试时间',
    fpublished_time DATETIME NULL COMMENT '发布时间',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_botp_outbox_publish (fstatus, fnext_retry_time, fcreate_time),
    KEY idx_matrix_botp_outbox_aggregate (faggregate_type, faggregate_id)
) COMMENT='BOTP Outbox事件';
