-- P0-IMP-03: PurchaseInbound -> AP Estimate -> Accounting Event -> Voucher Draft
-- New objects follow docs/specs/database-naming-convention.md.
-- Assumption: fi-service datasource is the matrix_fi database so that new accounting tables
-- and the historical bizfi_fi_voucher tables participate in one local transaction.

CREATE TABLE IF NOT EXISTS matrix_fi_inbox_event (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fconsumer_code VARCHAR(100) NOT NULL,
    fevent_id VARCHAR(100) NOT NULL,
    fevent_type VARCHAR(100) NOT NULL,
    fevent_version INT NOT NULL,
    fproducer_service VARCHAR(100) NULL,
    fsource_document_type VARCHAR(100) NULL,
    fsource_document_id VARCHAR(100) NULL,
    fpayload_json JSON NULL,
    fstatus VARCHAR(32) NOT NULL COMMENT 'PROCESSING/PROCESSED/FAILED',
    ferror_message VARCHAR(1000) NULL,
    freceived_time DATETIME NOT NULL,
    fprocessed_time DATETIME NULL,
    fpayable_id BIGINT NULL,
    faccounting_event_id VARCHAR(100) NULL,
    fvoucher_id BIGINT NULL,
    fvoucher_number VARCHAR(100) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_inbox_consumer_event (fconsumer_code, fevent_id),
    KEY idx_matrix_fi_inbox_status_time (fstatus, fmodify_time),
    KEY idx_matrix_fi_inbox_source (fsource_document_type, fsource_document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FI业务事件消费Inbox';

CREATE TABLE IF NOT EXISTS matrix_fi_ap_payable (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(100) NOT NULL,
    ftype VARCHAR(32) NOT NULL COMMENT 'ESTIMATE/FORMAL',
    fdate DATE NOT NULL,
    fbusiness_partner_id VARCHAR(100) NOT NULL,
    fbusiness_partner_code VARCHAR(100) NULL,
    fbusiness_partner_name VARCHAR(255) NULL,
    fcurrency_code VARCHAR(20) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    fopen_amount DECIMAL(20,2) NOT NULL,
    fsettled_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL COMMENT 'OPEN/PARTIAL_SETTLED/SETTLED/CLOSED',
    fapproval_status VARCHAR(32) NOT NULL,
    faccounting_status VARCHAR(32) NOT NULL COMMENT 'PENDING/VOUCHER_GENERATED/POSTED/FAILED',
    fsource_system_code VARCHAR(64) NOT NULL,
    fsource_document_type VARCHAR(100) NOT NULL,
    fsource_document_id VARCHAR(100) NOT NULL,
    fsource_document_no VARCHAR(100) NULL,
    fbusiness_event_id VARCHAR(100) NOT NULL,
    faccounting_event_id VARCHAR(100) NULL,
    fvoucher_id BIGINT NULL,
    fvoucher_number VARCHAR(100) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_ap_payable_event (ftenant_id, fbusiness_event_id),
    UNIQUE KEY uk_matrix_fi_ap_payable_number (ftenant_id, fnumber),
    KEY idx_matrix_fi_ap_payable_partner_status (ftenant_id, fbusiness_partner_id, fstatus),
    KEY idx_matrix_fi_ap_payable_source (ftenant_id, fsource_document_type, fsource_document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付单（含暂估/正式）';

CREATE TABLE IF NOT EXISTS matrix_fi_ap_payable_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpayable_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fsource_entry_id VARCHAR(100) NOT NULL,
    fpurchase_order_id VARCHAR(100) NULL,
    fpurchase_order_entry_id VARCHAR(100) NULL,
    fmaterial_id VARCHAR(100) NULL,
    fmaterial_code VARCHAR(100) NULL,
    fmaterial_name VARCHAR(255) NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    fwarehouse_id VARCHAR(100) NULL,
    fproject_id VARCHAR(100) NULL,
    fcost_center_id VARCHAR(100) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_ap_payable_entry_line (fpayable_id, fline_no),
    UNIQUE KEY uk_matrix_fi_ap_payable_entry_source (fpayable_id, fsource_entry_id),
    KEY idx_matrix_fi_ap_payable_entry_po (fpurchase_order_id, fpurchase_order_entry_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应付分录';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_event (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    faccounting_org_id BIGINT NOT NULL,
    faccounting_event_id VARCHAR(100) NOT NULL,
    faccounting_event_type VARCHAR(120) NOT NULL,
    fbusiness_event_id VARCHAR(100) NOT NULL,
    fbusiness_event_type VARCHAR(100) NOT NULL,
    fsequence_no INT NOT NULL DEFAULT 1,
    fbook_id VARCHAR(100) NOT NULL,
    fsource_system_code VARCHAR(64) NOT NULL,
    fsource_document_type VARCHAR(100) NOT NULL,
    fsource_document_id VARCHAR(100) NOT NULL,
    fsource_document_no VARCHAR(100) NULL,
    fbusiness_date DATE NULL,
    faccounting_date DATE NOT NULL,
    fcorrelation_id VARCHAR(100) NULL,
    fcausation_id VARCHAR(100) NULL,
    frule_code VARCHAR(100) NULL,
    frule_version INT NULL,
    fsource_payload_hash CHAR(64) NULL,
    fstatus VARCHAR(32) NOT NULL,
    fstage VARCHAR(64) NOT NULL,
    ffacts_json JSON NOT NULL,
    fvoucher_id BIGINT NULL,
    fvoucher_number VARCHAR(100) NULL,
    ferror_code VARCHAR(100) NULL,
    ferror_message VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_event_code (faccounting_event_id),
    UNIQUE KEY uk_matrix_fi_accounting_event_biz (ftenant_id, fbusiness_event_id, faccounting_event_type, fsequence_no),
    KEY idx_matrix_fi_accounting_event_status (fstatus, fstage, fmodify_time),
    KEY idx_matrix_fi_accounting_event_source (ftenant_id, fsource_document_type, fsource_document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计事件';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_event_entry (
    fid BIGINT NOT NULL,
    faccounting_event_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fsource_entry_id VARCHAR(100) NULL,
    fdirection VARCHAR(16) NOT NULL COMMENT 'DEBIT/CREDIT',
    faccount_key VARCHAR(100) NULL,
    fresolved_account_code VARCHAR(100) NOT NULL,
    fsummary VARCHAR(500) NULL,
    fdebit_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fcredit_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fcurrency_code VARCHAR(20) NULL,
    frate DECIMAL(20,8) NOT NULL DEFAULT 1,
    foriginal_amount DECIMAL(20,2) NULL,
    frule_entry_id BIGINT NULL,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_event_entry_line (faccounting_event_id, fline_no),
    KEY idx_matrix_fi_accounting_event_entry_source (fsource_entry_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计事件核算分录';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_event_dimension (
    fid BIGINT NOT NULL,
    faccounting_event_id BIGINT NOT NULL,
    faccounting_event_entry_id BIGINT NOT NULL,
    fdimension_code VARCHAR(100) NOT NULL,
    fdimension_value_id VARCHAR(100) NOT NULL,
    fdimension_value_code VARCHAR(100) NULL,
    fdimension_value_name VARCHAR(255) NULL,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_event_dimension (faccounting_event_entry_id, fdimension_code),
    KEY idx_matrix_fi_accounting_event_dimension_value (fdimension_code, fdimension_value_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计事件辅助核算维度';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_rule (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NULL,
    forg_id BIGINT NULL,
    frule_code VARCHAR(100) NOT NULL,
    frule_name VARCHAR(255) NOT NULL,
    fevent_type VARCHAR(120) NOT NULL,
    fpriority INT NOT NULL DEFAULT 0,
    fsource VARCHAR(32) NOT NULL COMMENT 'FORMAL/COMPATIBILITY',
    fstatus VARCHAR(32) NOT NULL,
    feffective_date DATE NULL,
    fexpiry_date DATE NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_rule_code (frule_code),
    KEY idx_matrix_fi_accounting_rule_match (fevent_type, fstatus, fpriority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核算规则';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_rule_version (
    fid BIGINT NOT NULL,
    frule_id BIGINT NOT NULL,
    fversion_no INT NOT NULL,
    fbook_id VARCHAR(100) NULL,
    fstatus VARCHAR(32) NOT NULL,
    fsource VARCHAR(32) NOT NULL,
    fdefinition_hash CHAR(64) NULL,
    fpublished_time DATETIME NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_rule_version (frule_id, fversion_no),
    KEY idx_matrix_fi_accounting_rule_version_status (frule_id, fstatus)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核算规则不可变版本';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_rule_entry (
    fid BIGINT NOT NULL,
    frule_version_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fscope VARCHAR(16) NOT NULL COMMENT 'HEADER/ENTRY',
    fdirection VARCHAR(16) NOT NULL COMMENT 'DEBIT/CREDIT',
    faccount_source_type VARCHAR(16) NOT NULL COMMENT 'FIXED/MAPPING',
    faccount_key VARCHAR(100) NULL,
    faccount_code VARCHAR(100) NULL,
    famount_expression VARCHAR(255) NOT NULL,
    fsummary_template VARCHAR(500) NULL,
    fcurrency_expression VARCHAR(255) NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_rule_entry_line (frule_version_id, fline_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核算规则分录';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_rule_dimension (
    fid BIGINT NOT NULL,
    frule_version_id BIGINT NOT NULL,
    frule_entry_id BIGINT NOT NULL,
    fdimension_code VARCHAR(100) NOT NULL,
    fsource_path VARCHAR(255) NOT NULL,
    frequired TINYINT NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_rule_dimension (frule_entry_id, fdimension_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核算规则辅助维度';

CREATE TABLE IF NOT EXISTS matrix_fi_account_mapping (
    fid BIGINT NOT NULL,
    fmapping_code VARCHAR(100) NOT NULL,
    ftenant_id VARCHAR(64) NULL,
    forg_id BIGINT NULL,
    fbook_id VARCHAR(100) NULL,
    faccount_key VARCHAR(100) NOT NULL,
    faccount_code VARCHAR(100) NOT NULL,
    fpriority INT NOT NULL DEFAULT 0,
    fsource VARCHAR(32) NOT NULL COMMENT 'FORMAL/COMPATIBILITY',
    fstatus VARCHAR(32) NOT NULL,
    feffective_date DATE NULL,
    fexpiry_date DATE NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_account_mapping_code (fmapping_code),
    KEY idx_matrix_fi_account_mapping_match (faccount_key, fstatus, fpriority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计科目映射';

CREATE TABLE IF NOT EXISTS matrix_fi_voucher_line_dimension (
    fid BIGINT NOT NULL,
    fvoucher_id BIGINT NOT NULL,
    fvoucher_line_id BIGINT NOT NULL,
    fdimension_code VARCHAR(100) NOT NULL,
    fdimension_value_id VARCHAR(100) NOT NULL,
    fdimension_value_code VARCHAR(100) NULL,
    fdimension_value_name VARCHAR(255) NULL,
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_voucher_line_dimension (fvoucher_line_id, fdimension_code),
    KEY idx_matrix_fi_voucher_dimension_value (fdimension_code, fdimension_value_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证分录辅助核算维度';

CREATE TABLE IF NOT EXISTS matrix_fi_accounting_trace (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fbusiness_event_id VARCHAR(100) NOT NULL,
    fbusiness_event_type VARCHAR(100) NOT NULL,
    fsource_system_code VARCHAR(64) NOT NULL,
    fsource_document_type VARCHAR(100) NOT NULL,
    fsource_document_id VARCHAR(100) NOT NULL,
    fsource_document_no VARCHAR(100) NULL,
    fpayable_id BIGINT NULL,
    faccounting_event_id VARCHAR(100) NOT NULL,
    frule_code VARCHAR(100) NOT NULL,
    frule_version INT NOT NULL,
    fvoucher_id BIGINT NULL,
    fvoucher_number VARCHAR(100) NULL,
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_fi_accounting_trace_event (ftenant_id, fbusiness_event_id, faccounting_event_id),
    KEY idx_matrix_fi_accounting_trace_source (fsource_document_type, fsource_document_id),
    KEY idx_matrix_fi_accounting_trace_voucher (fvoucher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='业务事件到会计结果穿透轨迹';

-- Existing OpenAPI V3 already adds this unique key on the historical voucher table:
-- UNIQUE (tenant_id, source_request_id).
-- P0-IMP-03 reuses source_request_id with ACCOUNTING:{accountingEventId}:VOUCHER:0.
