spring:
  application:
    name: base-service
  profiles:
    active: dev
  config:
    import: "nacos:${spring.application.name}"
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.216.168:8848
        namespace: public
      config:
        server-addr: 117.72.216.168:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: public
