-- P0-IMP-04 SupplierInvoice
-- Database: matrix_erp

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_invoice (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    finvoice_no VARCHAR(128) NOT NULL,
    finvoice_code VARCHAR(64) NULL,
    finvoice_date DATE NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(128) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL,
    fapproval_status VARCHAR(32) NOT NULL,
    fmatch_status VARCHAR(32) NOT NULL,
    faccounting_status VARCHAR(32) NOT NULL,
    fmatch_request_id VARCHAR(128) NULL,
    freconciliation_batch_id BIGINT NULL,
    fmatch_summary_json JSON NULL,
    fmatch_time DATETIME NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_erp_supplier_invoice_number (ftenant_id, fnumber, fdelete_flag),
    UNIQUE KEY uk_erp_supplier_invoice_external (ftenant_id, fbusiness_partner_id, finvoice_no, fdelete_flag),
    KEY idx_erp_supplier_invoice_status (ftenant_id, forg_id, fapproval_status, fmatch_status, finvoice_date),
    KEY idx_erp_supplier_invoice_reconciliation (ftenant_id, freconciliation_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商采购发票';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_invoice_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fsupplier_invoice_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(128) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_rate DECIMAL(10,6) NOT NULL DEFAULT 0,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fmatch_status VARCHAR(32) NOT NULL,
    freconciliation_case_id BIGINT NULL,
    fmatched_inbound_quantity DECIMAL(20,6) NULL,
    fdifference_codes VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_erp_supplier_invoice_entry_line (fsupplier_invoice_id, fline_no, fdelete_flag),
    KEY idx_erp_supplier_invoice_entry_po (ftenant_id, fpurchase_order_entry_id),
    KEY idx_erp_supplier_invoice_entry_case (ftenant_id, freconciliation_case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商采购发票分录';
