CREATE DATABASE IF NOT EXISTS matrix_erp
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_contract (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '采购合同号',
    fdate DATE NOT NULL COMMENT '合同日期',
    ftitle VARCHAR(255) NULL COMMENT '合同标题',
    fsourcing_award_id BIGINT NOT NULL COMMENT '来源定标ID',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '供应商Business Partner ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '供应商名称快照',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '合同币种',
    fstart_date DATE NULL COMMENT '合同开始日期',
    fend_date DATE NULL COMMENT '合同结束日期',
    fpayment_term_code VARCHAR(64) NULL COMMENT '付款条件编码',
    fdelivery_term_code VARCHAR(64) NULL COMMENT '交付条款编码',
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '合同总数量',
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '未税总额',
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '含税总额',
    fstatus VARCHAR(32) NOT NULL COMMENT '生命周期 DRAFT/EFFECTIVE',
    fapproval_status VARCHAR(32) NOT NULL COMMENT '审批状态 DRAFT/SUBMITTED/APPROVED/REJECTED',
    fexecution_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '执行状态 NONE/ORDERING/COMPLETE',
    fworkflow_instance_id VARCHAR(128) NULL COMMENT '工作流实例ID',
    freject_reason VARCHAR(1000) NULL COMMENT '驳回原因',
    fapproved_by BIGINT NULL COMMENT '最终审批人',
    fapproved_time DATETIME NULL COMMENT '最终审批时间',
    fremark VARCHAR(1000) NULL COMMENT '合同备注',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_contract_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_purchase_contract_partner (ftenant_id, fbusiness_partner_id, fdate),
    KEY idx_matrix_erp_purchase_contract_award (ftenant_id, fsourcing_award_id),
    KEY idx_matrix_erp_purchase_contract_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='采购合同主表';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_contract_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fpurchase_contract_id BIGINT NOT NULL COMMENT '采购合同ID',
    fline_no INT NOT NULL COMMENT '行号',
    fsourcing_award_entry_id BIGINT NOT NULL COMMENT '来源定标分录ID',
    frfq_entry_id BIGINT NOT NULL COMMENT '来源询价分录ID',
    fpurchase_request_id BIGINT NOT NULL COMMENT '来源采购申请ID',
    fpurchase_request_entry_id BIGINT NOT NULL COMMENT '来源采购申请分录ID',
    fmaterial_id BIGINT NOT NULL COMMENT '物料ID',
    fmaterial_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
    fmaterial_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
    fspecification VARCHAR(255) NULL COMMENT '规格型号快照',
    funit_id BIGINT NULL COMMENT '计量单位ID',
    fquantity DECIMAL(20,6) NOT NULL COMMENT '合同数量',
    funit_price DECIMAL(20,6) NOT NULL COMMENT '未税单价',
    ftax_rate DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税率 0-1',
    fnet_amount DECIMAL(20,2) NOT NULL COMMENT '未税金额',
    ftax_amount DECIMAL(20,2) NOT NULL COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL COMMENT '含税金额',
    fplanned_delivery_date DATE NULL COMMENT '计划交货日期',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    fordered_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计转采购订单数量',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_contract_entry_award (fpurchase_contract_id, fsourcing_award_entry_id, fdelete_flag),
    KEY idx_matrix_erp_purchase_contract_entry_contract (fpurchase_contract_id, fline_no),
    KEY idx_matrix_erp_purchase_contract_entry_award_source (ftenant_id, fsourcing_award_entry_id),
    KEY idx_matrix_erp_purchase_contract_entry_request (ftenant_id, fpurchase_request_id, fpurchase_request_entry_id)
) COMMENT='采购合同分录';
