CREATE DATABASE IF NOT EXISTS matrix_erp
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_procurement_rfq (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '询价单号',
    fdate DATE NOT NULL COMMENT '询价日期',
    ftitle VARCHAR(255) NULL COMMENT '询价主题',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '报价币种',
    fquotation_deadline DATETIME NULL COMMENT '报价截止时间',
    fstatus VARCHAR(32) NOT NULL COMMENT '状态 DRAFT/PUBLISHED/CLOSED/CANCELLED',
    fpublished_time DATETIME NULL COMMENT '发布时间',
    fclosed_time DATETIME NULL COMMENT '关闭时间',
    fremark VARCHAR(1000) NULL COMMENT '备注',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_procurement_rfq_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_procurement_rfq_status (ftenant_id, forg_id, fstatus, fdate)
) COMMENT='采购询价单';

CREATE TABLE IF NOT EXISTS matrix_erp_procurement_rfq_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    frfq_id BIGINT NOT NULL COMMENT '询价单ID',
    fline_no INT NOT NULL COMMENT '行号',
    fpurchase_request_id BIGINT NOT NULL COMMENT '采购申请ID',
    fpurchase_request_entry_id BIGINT NOT NULL COMMENT '采购申请分录ID',
    fmaterial_id BIGINT NOT NULL COMMENT '物料ID',
    fmaterial_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
    fmaterial_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
    fspecification VARCHAR(255) NULL COMMENT '规格型号快照',
    funit_id BIGINT NULL COMMENT '计量单位ID',
    fquantity DECIMAL(20,6) NOT NULL COMMENT '本次询价数量',
    fawarded_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已定标数量',
    frequired_date DATE NULL COMMENT '需求日期',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_procurement_rfq_entry_request (frfq_id, fpurchase_request_entry_id, fdelete_flag),
    KEY idx_matrix_erp_procurement_rfq_entry_rfq (frfq_id, fline_no),
    KEY idx_matrix_erp_procurement_rfq_entry_request (ftenant_id, fpurchase_request_id, fpurchase_request_entry_id)
) COMMENT='采购询价分录';

CREATE TABLE IF NOT EXISTS matrix_erp_procurement_rfq_supplier (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    frfq_id BIGINT NOT NULL COMMENT '询价单ID',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '供应商Business Partner ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '供应商名称快照',
    fstatus VARCHAR(32) NOT NULL DEFAULT 'INVITED' COMMENT 'INVITED',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_procurement_rfq_supplier (frfq_id, fbusiness_partner_id, fdelete_flag),
    KEY idx_matrix_erp_procurement_rfq_supplier_partner (ftenant_id, fbusiness_partner_id)
) COMMENT='询价邀请供应商';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_quote (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    frfq_id BIGINT NOT NULL COMMENT '询价单ID',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '供应商Business Partner ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '供应商名称快照',
    fquote_no VARCHAR(100) NOT NULL COMMENT '供应商报价号',
    fquote_date DATE NOT NULL COMMENT '报价日期',
    fvalid_until DATE NULL COMMENT '报价有效期',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '币种',
    fdelivery_days INT NULL COMMENT '承诺交期天数',
    fpayment_terms VARCHAR(255) NULL COMMENT '付款条件',
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '未税总额',
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '含税总额',
    fstatus VARCHAR(32) NOT NULL COMMENT 'DRAFT/SUBMITTED/WITHDRAWN',
    fsubmitted_time DATETIME NULL COMMENT '提交时间',
    fremark VARCHAR(1000) NULL COMMENT '备注',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_supplier_quote_supplier (frfq_id, fbusiness_partner_id, fdelete_flag),
    UNIQUE KEY uk_matrix_erp_supplier_quote_no (ftenant_id, fquote_no),
    KEY idx_matrix_erp_supplier_quote_status (ftenant_id, frfq_id, fstatus)
) COMMENT='供应商报价';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_quote_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fquote_id BIGINT NOT NULL COMMENT '报价ID',
    frfq_entry_id BIGINT NOT NULL COMMENT '询价分录ID',
    fline_no INT NOT NULL COMMENT '行号',
    fquantity DECIMAL(20,6) NOT NULL COMMENT '报价数量',
    fawarded_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已定标数量',
    funit_price DECIMAL(20,6) NOT NULL COMMENT '未税单价',
    ftax_rate DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税率 0-1',
    fnet_amount DECIMAL(20,2) NOT NULL COMMENT '未税金额',
    ftax_amount DECIMAL(20,2) NOT NULL COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL COMMENT '含税金额',
    fdelivery_date DATE NULL COMMENT '承诺交货日期',
    fremark VARCHAR(1000) NULL COMMENT '行备注',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_supplier_quote_entry (fquote_id, frfq_entry_id, fdelete_flag),
    KEY idx_matrix_erp_supplier_quote_entry_rfq (ftenant_id, frfq_entry_id)
) COMMENT='供应商报价分录';

CREATE TABLE IF NOT EXISTS matrix_erp_sourcing_award (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    frfq_id BIGINT NOT NULL COMMENT '询价单ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '定标单号',
    fdate DATE NOT NULL COMMENT '定标日期',
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '定标含税总额',
    fstatus VARCHAR(32) NOT NULL COMMENT 'CONFIRMED/CANCELLED',
    fremark VARCHAR(1000) NULL COMMENT '定标说明',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sourcing_award_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_sourcing_award_rfq (ftenant_id, frfq_id, fdate)
) COMMENT='采购定标事实';

CREATE TABLE IF NOT EXISTS matrix_erp_sourcing_award_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    faward_id BIGINT NOT NULL COMMENT '定标单ID',
    fline_no INT NOT NULL COMMENT '行号',
    frfq_entry_id BIGINT NOT NULL COMMENT '询价分录ID',
    fquote_id BIGINT NOT NULL COMMENT '报价ID',
    fquote_entry_id BIGINT NOT NULL COMMENT '报价分录ID',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '中标供应商ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '中标供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '中标供应商名称快照',
    fawarded_quantity DECIMAL(20,6) NOT NULL COMMENT '定标数量',
    funit_price DECIMAL(20,6) NOT NULL COMMENT '未税单价',
    ftax_rate DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '税率 0-1',
    fnet_amount DECIMAL(20,2) NOT NULL COMMENT '未税金额',
    ftax_amount DECIMAL(20,2) NOT NULL COMMENT '税额',
    fgross_amount DECIMAL(20,2) NOT NULL COMMENT '含税金额',
    freason VARCHAR(1000) NULL COMMENT '定标原因',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_sourcing_award_entry_award (faward_id, fline_no),
    KEY idx_matrix_erp_sourcing_award_entry_source (ftenant_id, frfq_entry_id, fquote_entry_id)
) COMMENT='采购定标分录';
