CREATE DATABASE IF NOT EXISTS matrix_erp
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_request (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '需求/采购组织ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '采购申请单号',
    fdate DATE NOT NULL COMMENT '申请日期',
    frequester_id BIGINT NULL COMMENT '申请人ID',
    frequest_department_id BIGINT NULL COMMENT '需求部门ID',
    frequest_type VARCHAR(32) NOT NULL DEFAULT 'OTHER' COMMENT '申请类型 PROJECT/RND/OPERATION/OTHER',
    fpurpose VARCHAR(1000) NULL COMMENT '采购用途/需求说明',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '预算币种',
    fbudget_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '采购预算金额',
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '申请总数量',
    festimated_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '预计采购金额',
    frequired_date DATE NULL COMMENT '总体需求日期',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    fsource_document_type VARCHAR(64) NULL COMMENT '来源单据类型',
    fsource_document_id VARCHAR(128) NULL COMMENT '来源单据ID',
    fsource_document_no VARCHAR(128) NULL COMMENT '来源单据号',
    fstatus VARCHAR(32) NOT NULL COMMENT '生命周期 DRAFT/EFFECTIVE/CANCELLED',
    fapproval_status VARCHAR(32) NOT NULL COMMENT '审批状态 DRAFT/SUBMITTED/APPROVED/REJECTED',
    fexecution_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '执行状态 NONE/SOURCING/CONTRACTING/ORDERING/COMPLETE',
    fworkflow_instance_id VARCHAR(128) NULL COMMENT '工作流实例ID',
    freject_reason VARCHAR(1000) NULL COMMENT '驳回原因',
    fapproved_by BIGINT NULL COMMENT '最终审批人',
    fapproved_time DATETIME NULL COMMENT '最终审批时间',
    fcreate_by BIGINT NULL COMMENT '创建人ID',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人ID',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_request_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_purchase_request_status (ftenant_id, forg_id, fstatus, fapproval_status),
    KEY idx_matrix_erp_purchase_request_requester (ftenant_id, frequester_id, fdate),
    KEY idx_matrix_erp_purchase_request_project (ftenant_id, fproject_id)
) COMMENT='采购申请主表';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_request_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '组织ID',
    fpurchase_request_id BIGINT NOT NULL COMMENT '采购申请ID',
    fline_no INT NOT NULL COMMENT '行号',
    fmaterial_id BIGINT NOT NULL COMMENT '物料ID',
    fmaterial_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
    fmaterial_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
    fspecification VARCHAR(255) NULL COMMENT '规格型号快照',
    funit_id BIGINT NULL COMMENT '计量单位ID',
    fquantity DECIMAL(20,6) NOT NULL COMMENT '申请数量',
    festimated_unit_price DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '预计不含税单价',
    festimated_amount DECIMAL(20,2) NOT NULL DEFAULT 0 COMMENT '预计金额',
    frequired_date DATE NULL COMMENT '需求日期',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    fsourced_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已寻源数量',
    fordered_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '已下单数量',
    fcreate_by BIGINT NULL COMMENT '创建人ID',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人ID',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_request_entry_request (fpurchase_request_id, fline_no),
    KEY idx_matrix_erp_purchase_request_entry_material (ftenant_id, fmaterial_id)
) COMMENT='采购申请分录表';
