USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_delivery_plan (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '交付计划号',
    fdate DATE NOT NULL COMMENT '计划日期',
    fpurchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    fpurchase_order_no VARCHAR(64) NOT NULL COMMENT '采购订单号快照',
    fbusiness_partner_id BIGINT NOT NULL COMMENT '供应商ID',
    fbusiness_partner_code VARCHAR(64) NOT NULL COMMENT '供应商编码快照',
    fbusiness_partner_name VARCHAR(255) NOT NULL COMMENT '供应商名称快照',
    fcurrency_code VARCHAR(32) NOT NULL COMMENT '币种',
    fstatus VARCHAR(32) NOT NULL COMMENT 'DRAFT/PUBLISHED/CHANGE_PROPOSED/CONFIRMED/PARTIAL/COMPLETE/REJECTED/CANCELLED',
    fcurrent_response_id BIGINT NULL COMMENT '当前供应商响应ID',
    fpublished_time DATETIME NULL COMMENT '发布时间',
    fconfirmed_time DATETIME NULL COMMENT '确认时间',
    fremark VARCHAR(1000) NULL COMMENT '备注',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_delivery_plan_number (ftenant_id, fnumber),
    UNIQUE KEY uk_matrix_erp_purchase_delivery_plan_order (ftenant_id, fpurchase_order_id),
    KEY idx_matrix_erp_purchase_delivery_plan_status (ftenant_id, forg_id, fstatus, fdate)
) COMMENT='采购交付计划';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_delivery_plan_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fdelivery_plan_id BIGINT NOT NULL COMMENT '交付计划ID',
    fline_no INT NOT NULL COMMENT '计划行号',
    fpurchase_order_id BIGINT NOT NULL COMMENT '采购订单ID',
    fpurchase_order_entry_id BIGINT NOT NULL COMMENT '采购订单分录ID',
    fmaterial_id BIGINT NOT NULL COMMENT '物料ID',
    fmaterial_code VARCHAR(64) NOT NULL COMMENT '物料编码快照',
    fmaterial_name VARCHAR(255) NOT NULL COMMENT '物料名称快照',
    fspecification VARCHAR(255) NULL COMMENT '规格型号快照',
    funit_id BIGINT NULL COMMENT '计量单位ID',
    fplanned_quantity DECIMAL(20,6) NOT NULL COMMENT '采购方计划交付数量',
    fplanned_delivery_date DATE NOT NULL COMMENT '采购方计划交付日期',
    fcommitted_quantity DECIMAL(20,6) NULL COMMENT '供应商最新承诺数量',
    fcommitted_delivery_date DATE NULL COMMENT '供应商最新承诺日期',
    fresponse_status VARCHAR(32) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/CONFIRMED/CHANGED/REJECTED',
    freceived_quantity DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '累计实际收货数量',
    flatest_response_entry_id BIGINT NULL COMMENT '最新响应分录ID',
    fproject_id BIGINT NULL COMMENT '项目ID',
    fcost_center_id BIGINT NULL COMMENT '成本中心ID',
    fcreate_by BIGINT NULL COMMENT '创建人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_delivery_plan_entry_plan (fdelivery_plan_id, fline_no),
    KEY idx_matrix_erp_delivery_plan_entry_order (ftenant_id, fpurchase_order_id, fpurchase_order_entry_id)
) COMMENT='采购交付计划分录';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_delivery_response (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fdelivery_plan_id BIGINT NOT NULL COMMENT '交付计划ID',
    fnumber VARCHAR(64) NOT NULL COMMENT '供应商响应号',
    fdate DATE NOT NULL COMMENT '响应日期',
    fresponse_type VARCHAR(32) NOT NULL COMMENT 'CONFIRM/CHANGE/REJECT',
    fstatus VARCHAR(32) NOT NULL COMMENT 'RECORDED/APPLIED/REJECTED',
    fremark VARCHAR(1000) NULL COMMENT '响应说明',
    fcreate_by BIGINT NULL COMMENT '记录人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_supplier_delivery_response_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_supplier_delivery_response_plan (ftenant_id, fdelivery_plan_id, fdate)
) COMMENT='供应商交付响应';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_delivery_response_entry (
    fid BIGINT NOT NULL COMMENT '主键',
    ftenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
    forg_id BIGINT NOT NULL COMMENT '采购组织ID',
    fresponse_id BIGINT NOT NULL COMMENT '供应商响应ID',
    fline_no INT NOT NULL COMMENT '行号',
    fdelivery_plan_entry_id BIGINT NOT NULL COMMENT '交付计划分录ID',
    fcommitted_quantity DECIMAL(20,6) NULL COMMENT '供应商承诺数量',
    fcommitted_delivery_date DATE NULL COMMENT '供应商承诺日期',
    freason VARCHAR(1000) NULL COMMENT '变更/拒绝原因',
    fcreate_by BIGINT NULL COMMENT '记录人',
    fcreate_time DATETIME NOT NULL COMMENT '创建时间',
    fmodify_by BIGINT NULL COMMENT '修改人',
    fmodify_time DATETIME NULL COMMENT '修改时间',
    fdelete_flag TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    fversion INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_supplier_delivery_response_entry (fresponse_id, fdelivery_plan_entry_id, fdelete_flag),
    KEY idx_matrix_erp_supplier_delivery_response_entry_plan (ftenant_id, fdelivery_plan_entry_id)
) COMMENT='供应商交付响应分录';
