USE matrix_erp;

ALTER TABLE matrix_erp_purchase_inbound_entry
    ADD COLUMN freturned_quantity DECIMAL(20,6) NOT NULL DEFAULT 0
        COMMENT '累计已确认采购退货数量' AFTER fquantity;

ALTER TABLE matrix_erp_purchase_order_entry
    ADD COLUMN freturned_quantity DECIMAL(20,6) NOT NULL DEFAULT 0
        COMMENT '累计已确认采购退货数量' AFTER finbound_quantity;

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_return (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fpurchase_inbound_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fwarehouse_id BIGINT NULL,
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    ftotal_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    freason_type VARCHAR(32) NOT NULL COMMENT 'QUALITY/DAMAGE/WRONG_GOODS/OVER_DELIVERY/OTHER',
    freason VARCHAR(1000) NULL,
    fstatus VARCHAR(32) NOT NULL COMMENT 'DRAFT/CONFIRMED/CANCELLED',
    fapproval_status VARCHAR(32) NOT NULL COMMENT 'DRAFT/SUBMITTED/AUDITED/REJECTED',
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_return_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_purchase_return_inbound (ftenant_id, fpurchase_inbound_id),
    KEY idx_matrix_erp_purchase_return_order (ftenant_id, fpurchase_order_id),
    KEY idx_matrix_erp_purchase_return_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='采购退货单';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_return_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpurchase_return_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_inbound_id BIGINT NOT NULL,
    fpurchase_inbound_entry_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    fbatch_no VARCHAR(128) NULL,
    fwarehouse_id BIGINT NULL,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_return_entry_return (fpurchase_return_id, fline_no),
    KEY idx_matrix_erp_purchase_return_entry_inbound (ftenant_id, fpurchase_inbound_entry_id),
    KEY idx_matrix_erp_purchase_return_entry_order (ftenant_id, fpurchase_order_entry_id)
) COMMENT='采购退货分录';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_claim (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_return_id BIGINT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fclaim_type VARCHAR(32) NOT NULL COMMENT 'RETURN/QUALITY/DELAY/SHORTAGE/OTHER',
    frequested_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fagreed_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fdeducted_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fdeduction_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/PARTIAL/COMPLETE',
    freason VARCHAR(1000) NULL,
    fstatus VARCHAR(32) NOT NULL COMMENT 'DRAFT/CONFIRMED/CANCELLED',
    fapproval_status VARCHAR(32) NOT NULL COMMENT 'DRAFT/SUBMITTED/AUDITED/REJECTED',
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_supplier_claim_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_supplier_claim_order (ftenant_id, fpurchase_order_id),
    KEY idx_matrix_erp_supplier_claim_return (ftenant_id, fpurchase_return_id),
    KEY idx_matrix_erp_supplier_claim_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='供应商索赔单';

CREATE TABLE IF NOT EXISTS matrix_erp_supplier_claim_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fsupplier_claim_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fpurchase_return_entry_id BIGINT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    frequested_amount DECIMAL(20,2) NOT NULL,
    fagreed_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fdeducted_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    freason VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_supplier_claim_entry_claim (fsupplier_claim_id, fline_no),
    KEY idx_matrix_erp_supplier_claim_entry_order (ftenant_id, fpurchase_order_entry_id),
    KEY idx_matrix_erp_supplier_claim_entry_return (ftenant_id, fpurchase_return_entry_id)
) COMMENT='供应商索赔分录';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_deduction (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fsupplier_claim_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    freason VARCHAR(1000) NULL,
    fstatus VARCHAR(32) NOT NULL COMMENT 'DRAFT/CONFIRMED/CANCELLED',
    fapproval_status VARCHAR(32) NOT NULL COMMENT 'DRAFT/SUBMITTED/AUDITED/REJECTED',
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_purchase_deduction_number (ftenant_id, fnumber),
    KEY idx_matrix_erp_purchase_deduction_claim (ftenant_id, fsupplier_claim_id),
    KEY idx_matrix_erp_purchase_deduction_status (ftenant_id, forg_id, fstatus, fapproval_status)
) COMMENT='采购扣款单';

CREATE TABLE IF NOT EXISTS matrix_erp_purchase_deduction_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NOT NULL,
    fpurchase_deduction_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fsupplier_claim_entry_id BIGINT NOT NULL,
    fpurchase_order_id BIGINT NOT NULL,
    fpurchase_order_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    famount DECIMAL(20,2) NOT NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_purchase_deduction_entry_header (fpurchase_deduction_id, fline_no),
    KEY idx_matrix_erp_purchase_deduction_entry_claim (ftenant_id, fsupplier_claim_entry_id),
    KEY idx_matrix_erp_purchase_deduction_entry_order (ftenant_id, fpurchase_order_entry_id)
) COMMENT='采购扣款分录';
