USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_crm_lead (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fname VARCHAR(255) NOT NULL,
    fcompany_name VARCHAR(255) NULL,
    fcontact_name VARCHAR(128) NULL,
    fcontact_phone VARCHAR(64) NULL,
    fcontact_email VARCHAR(128) NULL,
    fsource VARCHAR(64) NULL,
    fowner_id BIGINT NULL,
    festimated_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fcurrency_code VARCHAR(32) NULL,
    fnext_action_date DATE NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'NEW',
    fqualified_time DATETIME NULL,
    fdisqualified_reason VARCHAR(500) NULL,
    fconverted_business_partner_id BIGINT NULL,
    fconverted_opportunity_id BIGINT NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_crm_lead_number (ftenant_id, fnumber, fdelete_flag),
    KEY idx_matrix_erp_crm_lead_owner_status (ftenant_id, fowner_id, fstatus),
    KEY idx_matrix_erp_crm_lead_source (ftenant_id, fsource, fstatus)
) COMMENT='CRM销售线索';

CREATE TABLE IF NOT EXISTS matrix_erp_crm_opportunity (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    flead_id BIGINT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fname VARCHAR(255) NOT NULL,
    fowner_id BIGINT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fexpected_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fexpected_close_date DATE NULL,
    fstage VARCHAR(32) NOT NULL,
    fprobability DECIMAL(5,2) NOT NULL DEFAULT 0,
    fnext_action_date DATE NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    flost_reason VARCHAR(500) NULL,
    fwon_time DATETIME NULL,
    flost_time DATETIME NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_crm_opportunity_number (ftenant_id, fnumber, fdelete_flag),
    KEY idx_matrix_erp_crm_opportunity_partner (ftenant_id, fbusiness_partner_id, fstatus),
    KEY idx_matrix_erp_crm_opportunity_owner_stage (ftenant_id, fowner_id, fstage, fstatus),
    KEY idx_matrix_erp_crm_opportunity_lead (ftenant_id, flead_id)
) COMMENT='CRM销售商机';
