USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_sales_quote (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fquote_type VARCHAR(16) NOT NULL DEFAULT 'QUOTE',
    ftender_reference VARCHAR(128) NULL,
    fopportunity_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fvalid_until DATE NOT NULL,
    fdelivery_term_code VARCHAR(64) NULL,
    fpayment_term_code VARCHAR(64) NULL,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    faccepted_by BIGINT NULL,
    faccepted_time DATETIME NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_quote_number (ftenant_id, fnumber, fdelete_flag),
    KEY idx_matrix_erp_sales_quote_opportunity (ftenant_id, fopportunity_id),
    KEY idx_matrix_erp_sales_quote_customer (ftenant_id, fbusiness_partner_id, fstatus)
) COMMENT='销售报价与投标报价';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_quote_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    fquote_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fmaterial_code VARCHAR(64) NULL,
    fdescription VARCHAR(512) NOT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    ftax_rate DECIMAL(7,4) NOT NULL,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_quote_entry_line (ftenant_id, fquote_id, fline_no),
    KEY idx_matrix_erp_sales_quote_entry_quote (ftenant_id, fquote_id)
) COMMENT='销售报价明细';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_contract (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    ftitle VARCHAR(255) NOT NULL,
    fquote_id BIGINT NOT NULL,
    fopportunity_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fstart_date DATE NOT NULL,
    fend_date DATE NOT NULL,
    fdelivery_term_code VARCHAR(64) NULL,
    fpayment_term_code VARCHAR(64) NULL,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fapproval_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fapproved_by BIGINT NULL,
    fapproved_time DATETIME NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_contract_number (ftenant_id, fnumber, fdelete_flag),
    UNIQUE KEY uk_matrix_erp_sales_contract_quote (ftenant_id, fquote_id, fdelete_flag),
    KEY idx_matrix_erp_sales_contract_customer (ftenant_id, fbusiness_partner_id, fstatus)
) COMMENT='销售合同';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_contract_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    fcontract_id BIGINT NOT NULL,
    fsource_quote_entry_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fmaterial_code VARCHAR(64) NULL,
    fdescription VARCHAR(512) NOT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    ftax_rate DECIMAL(7,4) NOT NULL,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fordered_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fdelivered_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    finvoiced_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fsettled_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fcreate_time DATETIME NOT NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_contract_entry_line (ftenant_id, fcontract_id, fline_no)
) COMMENT='销售合同履约与反写明细';

