USE matrix_erp;

CREATE TABLE IF NOT EXISTS matrix_erp_sales_quotation (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    fopportunity_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fquotation_type VARCHAR(32) NOT NULL,
    ftitle VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fvalid_until DATE NULL,
    fpayment_term_code VARCHAR(64) NULL,
    fdelivery_term_code VARCHAR(64) NULL,
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fapproval_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fcustomer_decision_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    fworkflow_instance_id VARCHAR(128) NULL,
    freject_reason VARCHAR(500) NULL,
    fcustomer_reject_reason VARCHAR(500) NULL,
    fsent_time DATETIME NULL,
    faccepted_time DATETIME NULL,
    fremark VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_quotation_number (ftenant_id, fnumber, fdelete_flag),
    KEY idx_matrix_erp_sales_quotation_opportunity (ftenant_id, fopportunity_id, fstatus),
    KEY idx_matrix_erp_sales_quotation_partner (ftenant_id, fbusiness_partner_id, fstatus),
    KEY idx_matrix_erp_sales_quotation_decision (ftenant_id, fcustomer_decision_status, fvalid_until)
) COMMENT='销售报价/投标单';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_quotation_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fsales_quotation_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    ftax_rate DECIMAL(10,6) NOT NULL DEFAULT 0,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fplanned_delivery_date DATE NULL,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    fcontract_reserved_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fcontracted_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_sales_quotation_entry_header (fsales_quotation_id, fline_no)
) COMMENT='销售报价/投标分录';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_contract (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fnumber VARCHAR(64) NOT NULL,
    fdate DATE NOT NULL,
    ftitle VARCHAR(255) NOT NULL,
    fopportunity_id BIGINT NOT NULL,
    fsales_quotation_id BIGINT NOT NULL,
    fbusiness_partner_id BIGINT NOT NULL,
    fbusiness_partner_code VARCHAR(64) NOT NULL,
    fbusiness_partner_name VARCHAR(255) NOT NULL,
    fcurrency_code VARCHAR(32) NOT NULL,
    fstart_date DATE NULL,
    fend_date DATE NULL,
    fpayment_term_code VARCHAR(64) NULL,
    fdelivery_term_code VARCHAR(64) NULL,
    ftotal_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fnet_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    ftax_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fgross_amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    fstatus VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fapproval_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fexecution_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    fworkflow_instance_id VARCHAR(128) NULL,
    freject_reason VARCHAR(500) NULL,
    fapproved_by BIGINT NULL,
    fapproved_time DATETIME NULL,
    fremark VARCHAR(1000) NULL,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    UNIQUE KEY uk_matrix_erp_sales_contract_number (ftenant_id, fnumber, fdelete_flag),
    KEY idx_matrix_erp_sales_contract_opportunity (ftenant_id, fopportunity_id, fstatus),
    KEY idx_matrix_erp_sales_contract_quotation (ftenant_id, fsales_quotation_id, fstatus),
    KEY idx_matrix_erp_sales_contract_partner (ftenant_id, fbusiness_partner_id, fstatus)
) COMMENT='销售合同';

CREATE TABLE IF NOT EXISTS matrix_erp_sales_contract_entry (
    fid BIGINT NOT NULL,
    ftenant_id VARCHAR(64) NOT NULL,
    forg_id BIGINT NULL,
    fsales_contract_id BIGINT NOT NULL,
    fline_no INT NOT NULL,
    fsales_quotation_entry_id BIGINT NOT NULL,
    fmaterial_id BIGINT NOT NULL,
    fmaterial_code VARCHAR(64) NOT NULL,
    fmaterial_name VARCHAR(255) NOT NULL,
    fspecification VARCHAR(255) NULL,
    funit_id BIGINT NULL,
    fquantity DECIMAL(20,6) NOT NULL,
    funit_price DECIMAL(20,6) NOT NULL,
    ftax_rate DECIMAL(10,6) NOT NULL DEFAULT 0,
    fnet_amount DECIMAL(20,2) NOT NULL,
    ftax_amount DECIMAL(20,2) NOT NULL,
    fgross_amount DECIMAL(20,2) NOT NULL,
    fplanned_delivery_date DATE NULL,
    fproject_id BIGINT NULL,
    fcost_center_id BIGINT NULL,
    fordered_quantity DECIMAL(20,6) NOT NULL DEFAULT 0,
    fcreate_by BIGINT NULL,
    fcreate_time DATETIME NOT NULL,
    fmodify_by BIGINT NULL,
    fmodify_time DATETIME NULL,
    fdelete_flag TINYINT NOT NULL DEFAULT 0,
    fversion INT NOT NULL DEFAULT 0,
    PRIMARY KEY (fid),
    KEY idx_matrix_erp_sales_contract_entry_header (fsales_contract_id, fline_no),
    KEY idx_matrix_erp_sales_contract_entry_quote (ftenant_id, fsales_quotation_entry_id)
) COMMENT='销售合同分录';
