CREATE TABLE IF NOT EXISTS bizfi_fi_internal_notice (
    fid BIGINT PRIMARY KEY AUTO_INCREMENT,
    fnotice_type VARCHAR(32) NOT NULL,
    fdoc_type_root VARCHAR(16) NULL,
    forg_id BIGINT NULL,
    fperiod VARCHAR(16) NULL,
    fstatus VARCHAR(16) NOT NULL,
    fseverity VARCHAR(16) NOT NULL,
    freference_key VARCHAR(128) NOT NULL,
    freference_type VARCHAR(64) NOT NULL,
    fsource_code VARCHAR(64) NULL,
    fcategory_code VARCHAR(64) NULL,
    fcounterparty VARCHAR(128) NULL,
    fvoucher_id BIGINT NULL,
    fvoucher_number VARCHAR(64) NULL,
    ftitle VARCHAR(200) NOT NULL,
    fmessage VARCHAR(500) NULL,
    fsuggestion VARCHAR(500) NULL,
    famount DECIMAL(18, 2) NULL,
    fopen_amount DECIMAL(18, 2) NULL,
    fsource_date DATE NULL,
    fdue_date DATE NULL,
    fowner VARCHAR(64) NULL,
    fnotice_time DATETIME NOT NULL,
    fupdate_time DATETIME NOT NULL,
    fresolved_time DATETIME NULL,
    fresolve_note VARCHAR(500) NULL,
    UNIQUE KEY uk_internal_notice_type_ref (fnotice_type, freference_key),
    KEY idx_internal_notice_type_status (fnotice_type, fstatus),
    KEY idx_internal_notice_root (fdoc_type_root),
    KEY idx_internal_notice_org_period (forg_id, fperiod)
);
