CREATE TABLE IF NOT EXISTS bizfi_ai_tool_execution (
  fid BIGINT PRIMARY KEY AUTO_INCREMENT,
  frequestid VARCHAR(64) NOT NULL,
  ftoolname VARCHAR(64) NOT NULL,
  fuserid BIGINT NOT NULL,
  forganizationid BIGINT NOT NULL,
  fperiod VARCHAR(16) NOT NULL,
  fstatus VARCHAR(32) NOT NULL,
  freadinessscore INT,
  fblockingcount INT,
  fwarningcount INT,
  fclosestatus VARCHAR(32),
  fdurationms BIGINT DEFAULT 0,
  ferrorcode VARCHAR(64),
  ferrormessage VARCHAR(500),
  fstarttime DATETIME NOT NULL,
  fendtime DATETIME,
  fcreatetime DATETIME NOT NULL,
  fmodifytime DATETIME NOT NULL,
  UNIQUE KEY uk_ai_tool_request (frequestid),
  KEY idx_ai_tool_user_time (fuserid, fcreatetime),
  KEY idx_ai_tool_org_period (forganizationid, fperiod),
  KEY idx_ai_tool_status_time (fstatus, fcreatetime)
);
