CREATE TABLE IF NOT EXISTS bizfi_fi_month_end_check_batch (
    fid BIGINT PRIMARY KEY AUTO_INCREMENT,
    fbatch_no VARCHAR(64) NOT NULL,
    forg BIGINT NULL,
    fperiod VARCHAR(16) NOT NULL,
    fperiod_source VARCHAR(32) NULL,
    fbase_currency VARCHAR(16) NULL,
    fcurrent_period VARCHAR(16) NULL,
    fperiod_status VARCHAR(32) NULL,
    fclose_status VARCHAR(32) NOT NULL,
    freadiness_score INT DEFAULT 0,
    fcan_close TINYINT(1) DEFAULT 0,
    fblocking_count INT DEFAULT 0,
    fwarning_count INT DEFAULT 0,
    fpending_count INT DEFAULT 0,
    fpassed_count INT DEFAULT 0,
    ftotal_check_count INT DEFAULT 0,
    fperiod_voucher_count INT DEFAULT 0,
    fposted_voucher_count INT DEFAULT 0,
    fpending_voucher_count INT DEFAULT 0,
    fexception_voucher_count INT DEFAULT 0,
    fapplication_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    fsnapshot_json LONGTEXT NOT NULL,
    fremark VARCHAR(512) NULL,
    fcreated_by VARCHAR(64) NULL,
    fcreated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    fsubmitted_by VARCHAR(64) NULL,
    fsubmitted_time DATETIME NULL,
    fapproved_by VARCHAR(64) NULL,
    fapproved_time DATETIME NULL,
    fupdate_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_month_end_check_batch_no (fbatch_no),
    KEY idx_month_end_check_batch_scope (forg, fperiod),
    KEY idx_month_end_check_batch_status (fapplication_status)
);

