CREATE TABLE IF NOT EXISTS bizfi_fi_base_config_item (
    fid BIGINT PRIMARY KEY AUTO_INCREMENT,
    forg BIGINT NULL,
    fcategory VARCHAR(64) NOT NULL,
    fcode VARCHAR(64) NOT NULL,
    fname VARCHAR(128) NOT NULL,
    fvalue VARCHAR(255) NULL,
    fstatus VARCHAR(32) DEFAULT 'ENABLED',
    fsort INT DEFAULT 0,
    fremark VARCHAR(255) NULL,
    fcreatetime DATETIME DEFAULT CURRENT_TIMESTAMP,
    fupdatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
