CREATE TABLE IF NOT EXISTS `bizfi_fi_arap_writeoff_log` (
  `fid` BIGINT NOT NULL AUTO_INCREMENT,
  `fplan_code` VARCHAR(64) NOT NULL,
  `fdoc_type_root` VARCHAR(8) NOT NULL,
  `fcounterparty` VARCHAR(128) NULL,
  `fmode` VARCHAR(32) NOT NULL,
  `fsource_doc_count` INT NOT NULL DEFAULT 0,
  `ftarget_doc_count` INT NOT NULL DEFAULT 0,
  `flink_count` INT NOT NULL DEFAULT 0,
  `ftotal_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `fstatus` VARCHAR(32) NOT NULL,
  `fmessage` VARCHAR(512) NULL,
  `foperator` VARCHAR(64) NULL,
  `foperate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`fid`),
  UNIQUE KEY `uk_arap_writeoff_log_plan` (`fplan_code`),
  KEY `idx_arap_writeoff_log_root_counterparty` (`fdoc_type_root`, `fcounterparty`),
  KEY `idx_arap_writeoff_log_time` (`foperate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `bizfi_fi_arap_writeoff_link` (
  `fid` BIGINT NOT NULL AUTO_INCREMENT,
  `flog_id` BIGINT NOT NULL,
  `fplan_code` VARCHAR(64) NOT NULL,
  `fdoc_type_root` VARCHAR(8) NOT NULL,
  `fcounterparty` VARCHAR(128) NOT NULL,
  `fsource_doc_id` BIGINT NOT NULL,
  `fsource_doc_number` VARCHAR(64) NOT NULL,
  `fsource_doc_type` VARCHAR(32) NOT NULL,
  `ftarget_doc_id` BIGINT NOT NULL,
  `ftarget_doc_number` VARCHAR(64) NOT NULL,
  `ftarget_doc_type` VARCHAR(32) NOT NULL,
  `famount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `fauto_flag` INT NOT NULL DEFAULT 1,
  `foperator` VARCHAR(64) NULL,
  `foperate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fremark` VARCHAR(512) NULL,
  PRIMARY KEY (`fid`),
  KEY `idx_arap_writeoff_link_log` (`flog_id`),
  KEY `idx_arap_writeoff_link_plan` (`fplan_code`),
  KEY `idx_arap_writeoff_link_source` (`fsource_doc_id`),
  KEY `idx_arap_writeoff_link_target` (`ftarget_doc_id`),
  KEY `idx_arap_writeoff_link_root_counterparty` (`fdoc_type_root`, `fcounterparty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
